version: '3.8'
services:
  app:
    ports:
      - '8080'

    build: 
      context: ./app
      dockerfile: multi-stage.dockerfile

    deploy:
      replicas: 4

  # reverse-proxy:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
