FROM node:latest as build
WORKDIR /app
COPY . /app
RUN npm i && npx tsc

FROM node:latest as execution
WORKDIR /app
COPY . /app
RUN useradd -ms /bin/bash seconduser
USER seconduser
CMD node build/index.js